# Base
line-length = 88
target-version = "py311"
extend-exclude = ["data/**", "resources/**", ".venv/**", ".git/**", ".pytest_cache/**"]

[lint]
# Lints úteis + import order (I)
select = ["E", "F", "I", "UP", "B"]
# Evita conflito com o formatador; quebre de linha fica a cargo do `ruff format`
ignore = ["E501"]

[lint.isort]
known-first-party = ["src"]
combine-as-imports = true
force-sort-within-sections = true

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
