name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: isort
        run: isort --check-only .

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]  # opcional: remova 3.10 se não quiser matriz
    env:
      # Evita chamadas externas nos testes de CI
      RUN_LIVE_API_TESTS: "0"
      OPENAI_API_KEY: ""
      SERPER_API_KEY: ""
      # Evita problemas de display com matplotlib
      MPLBACKEND: Agg
      # Execuções determinísticas de datas/horas
      TZ: UTC
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings -rA
      - name: Upload report artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-py${{ matrix.python-version }}
          path: |
            resources/reports/**
            resources/json/**
          if-no-files-found: ignore
