name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pip install ruff black isort
          ruff check .
          black --check .
          isort --check-only .
      - name: Run tests
        env:
          # Desliga testes live por padrão no CI
          RUN_LIVE_API_TESTS: "0"
        run: pytest -q
