name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Install dev deps (Ruff)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      # Ordenação de imports (isort-like)
      - name: Ruff (import order)
        run: ruff check --select I --diff .
      # Lint
      - name: Ruff (lint)
        run: ruff check .
      # Formatação (substitui Black)
      - name: Ruff (format check)
        run: ruff format --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.12"]
    env:
      RUN_LIVE_API_TESTS: "0"  # nunca chama serviços externos no CI
      OPENAI_API_KEY: ""
      SERPER_API_KEY: ""
      MPLBACKEND: Agg         # evita problemas de display no matplotlib
      TZ: UTC
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings -rA
      - name: Upload report artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-py${{ matrix.python-version }}
          path: |
            resources/reports/**
            resources/json/**
          if-no-files-found: ignore
